name: Application CI
on: [push, pull_request]
jobs:
  pipeline:
    name: mcp-diagram CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: maven-settings
        uses: s4u/maven-settings-action@v2
        with:
          servers: '[{"id": "github", "username": "github_actions", "password": "${GITHUB_TOKEN_REF}"}]'
          githubServer: false
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        env:
          GITHUB_TOKEN_REF: ${{ secrets.GH_PAT_FOR_ACTIONS_TOKEN }}
